package esi.roadside.assistance.provider.core.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object PurpleColors {
    private val primaryLight = Color(0xFF65558F)
    private val onPrimaryLight = Color(0xFFFFFFFF)
    private val primaryContainerLight = Color(0xFFEADDFF)
    private val onPrimaryContainerLight = Color(0xFF21005D)
    private val secondaryLight = Color(0xFF625B71)
    private val onSecondaryLight = Color(0xFFFFFFFF)
    private val secondaryContainerLight = Color(0xFFE8DEF8)
    private val onSecondaryContainerLight = Color(0xFF1D192B)
    private val tertiaryLight = Color(0xFF7D5260)
    private val onTertiaryLight = Color(0xFFFFFFFF)
    private val tertiaryContainerLight = Color(0xFFFFD8E4)
    private val onTertiaryContainerLight = Color(0xFF31111D)
    private val errorLight = Color(0xFFB3261E)
    private val onErrorLight = Color(0xFFFFFFFF)
    private val errorContainerLight = Color(0xFFF9DEDC)
    private val onErrorContainerLight = Color(0xFF410E0B)
    private val backgroundLight = Color(0xFFFEF7FF)
    private val onBackgroundLight = Color(0xFF1D1B20)
    private val surfaceLight = Color(0xFFFEF7FF)
    private val onSurfaceLight = Color(0xFF1D1B20)
    private val surfaceVariantLight = Color(0xFFE7E0EC)
    private val onSurfaceVariantLight = Color(0xFF49454F)
    private val outlineLight = Color(0xFF79747E)
    private val outlineVariantLight = Color(0xFFCAC4D0)
    private val scrimLight = Color(0xFF000000)
    private val inverseSurfaceLight = Color(0xFF322F35)
    private val inverseOnSurfaceLight = Color(0xFFF5EFF7)
    private val inversePrimaryLight = Color(0xFFD0BCFF)
    private val surfaceDimLight = Color(0xFFDED8E1)
    private val surfaceBrightLight = Color(0xFFFEF7FF)
    private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    private val surfaceContainerLowLight = Color(0xFFF7F2FA)
    private val surfaceContainerLight = Color(0xFFF3EDF7)
    private val surfaceContainerHighLight = Color(0xFFECE6F0)
    private val surfaceContainerHighestLight = Color(0xFFE6E0E9)

    private val primaryLightMediumContrast = Color(0xFF493971)
    private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightMediumContrast = Color(0xFF7B6BA7)
    private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryLightMediumContrast = Color(0xFF493971)
    private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightMediumContrast = Color(0xFF7C6BA7)
    private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryLightMediumContrast = Color(0xFF6B2F45)
    private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightMediumContrast = Color(0xFFA55F77)
    private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val errorLightMediumContrast = Color(0xFF6E2F2C)
    private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    private val errorContainerLightMediumContrast = Color(0xFFAA5F5A)
    private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    private val backgroundLightMediumContrast = Color(0xFFFDF7FF)
    private val onBackgroundLightMediumContrast = Color(0xFF1D1B20)
    private val surfaceLightMediumContrast = Color(0xFFFDF7FF)
    private val onSurfaceLightMediumContrast = Color(0xFF1D1B20)
    private val surfaceVariantLightMediumContrast = Color(0xFFE7E0EB)
    private val onSurfaceVariantLightMediumContrast = Color(0xFF45414A)
    private val outlineLightMediumContrast = Color(0xFF615D67)
    private val outlineVariantLightMediumContrast = Color(0xFF7D7983)
    private val scrimLightMediumContrast = Color(0xFF000000)
    private val inverseSurfaceLightMediumContrast = Color(0xFF322F35)
    private val inverseOnSurfaceLightMediumContrast = Color(0xFFF5EFF7)
    private val inversePrimaryLightMediumContrast = Color(0xFFCFBDFE)
    private val surfaceDimLightMediumContrast = Color(0xFFDED8E0)
    private val surfaceBrightLightMediumContrast = Color(0xFFFDF7FF)
    private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightMediumContrast = Color(0xFFF8F2FA)
    private val surfaceContainerLightMediumContrast = Color(0xFFF2ECF4)
    private val surfaceContainerHighLightMediumContrast = Color(0xFFECE6EE)
    private val surfaceContainerHighestLightMediumContrast = Color(0xFFE6E0E9)

    private val primaryLightHighContrast = Color(0xFF27174E)
    private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    private val primaryContainerLightHighContrast = Color(0xFF493971)
    private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryLightHighContrast = Color(0xFF27174E)
    private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    private val secondaryContainerLightHighContrast = Color(0xFF493971)
    private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryLightHighContrast = Color(0xFF420E24)
    private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    private val tertiaryContainerLightHighContrast = Color(0xFF6B2F45)
    private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    private val errorLightHighContrast = Color(0xFF440F0E)
    private val onErrorLightHighContrast = Color(0xFFFFFFFF)
    private val errorContainerLightHighContrast = Color(0xFF6E2F2C)
    private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    private val backgroundLightHighContrast = Color(0xFFFDF7FF)
    private val onBackgroundLightHighContrast = Color(0xFF1D1B20)
    private val surfaceLightHighContrast = Color(0xFFFDF7FF)
    private val onSurfaceLightHighContrast = Color(0xFF000000)
    private val surfaceVariantLightHighContrast = Color(0xFFE7E0EB)
    private val onSurfaceVariantLightHighContrast = Color(0xFF25232B)
    private val outlineLightHighContrast = Color(0xFF45414A)
    private val outlineVariantLightHighContrast = Color(0xFF45414A)
    private val scrimLightHighContrast = Color(0xFF000000)
    private val inverseSurfaceLightHighContrast = Color(0xFF322F35)
    private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    private val inversePrimaryLightHighContrast = Color(0xFFF1E8FF)
    private val surfaceDimLightHighContrast = Color(0xFFDED8E0)
    private val surfaceBrightLightHighContrast = Color(0xFFFDF7FF)
    private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    private val surfaceContainerLowLightHighContrast = Color(0xFFF8F2FA)
    private val surfaceContainerLightHighContrast = Color(0xFFF2ECF4)
    private val surfaceContainerHighLightHighContrast = Color(0xFFECE6EE)
    private val surfaceContainerHighestLightHighContrast = Color(0xFFE6E0E9)

    private val primaryDark = Color(0xFFD0BCFE)
    private val onPrimaryDark = Color(0xFF381E72)
    private val primaryContainerDark = Color(0xFF4F378B)
    private val onPrimaryContainerDark = Color(0xFFEADDFF)
    private val secondaryDark = Color(0xFFCCC2DC)
    private val onSecondaryDark = Color(0xFF332D41)
    private val secondaryContainerDark = Color(0xFF4A4458)
    private val onSecondaryContainerDark = Color(0xFFE8DEF8)
    private val tertiaryDark = Color(0xFFEFB8C8)
    private val onTertiaryDark = Color(0xFF492532)
    private val tertiaryContainerDark = Color(0xFF633B48)
    private val onTertiaryContainerDark = Color(0xFFFFD8E4)
    private val errorDark = Color(0xFFF2B8B5)
    private val onErrorDark = Color(0xFF601410)
    private val errorContainerDark = Color(0xFF8C1D18)
    private val onErrorContainerDark = Color(0xFFF9DEDC)
    private val backgroundDark = Color(0xFF141218)
    private val onBackgroundDark = Color(0xFFE6E0E9)
    private val surfaceDark = Color(0xFF141218)
    private val onSurfaceDark = Color(0xFFE6E0E9)
    private val surfaceVariantDark = Color(0xFF49454F)
    private val onSurfaceVariantDark = Color(0xFFCAC4D0)
    private val outlineDark = Color(0xFF938F99)
    private val outlineVariantDark = Color(0xFF49454F)
    private val scrimDark = Color(0xFF000000)
    private val inverseSurfaceDark = Color(0xFFE6E0E9)
    private val inverseOnSurfaceDark = Color(0xFF322F35)
    private val inversePrimaryDark = Color(0xFF6750A4)
    private val surfaceDimDark = Color(0xFF141218)
    private val surfaceBrightDark = Color(0xFF3B383E)
    private val surfaceContainerLowestDark = Color(0xFF0F0D13)
    private val surfaceContainerLowDark = Color(0xFF1D1B20)
    private val surfaceContainerDark = Color(0xFF211F26)
    private val surfaceContainerHighDark = Color(0xFF2B2930)
    private val surfaceContainerHighestDark = Color(0xFF36343B)

    private val primaryDarkMediumContrast = Color(0xFFD3C1FF)
    private val onPrimaryDarkMediumContrast = Color(0xFF1B0942)
    private val primaryContainerDarkMediumContrast = Color(0xFF9887C5)
    private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    private val secondaryDarkMediumContrast = Color(0xFFD3C1FF)
    private val onSecondaryDarkMediumContrast = Color(0xFF1B0942)
    private val secondaryContainerDarkMediumContrast = Color(0xFF9887C5)
    private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    private val tertiaryDarkMediumContrast = Color(0xFFFFB7CD)
    private val onTertiaryDarkMediumContrast = Color(0xFF330218)
    private val tertiaryContainerDarkMediumContrast = Color(0xFFC57B93)
    private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    private val errorDarkMediumContrast = Color(0xFFFFB9B3)
    private val onErrorDarkMediumContrast = Color(0xFF330405)
    private val errorContainerDarkMediumContrast = Color(0xFFCC7B74)
    private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    private val backgroundDarkMediumContrast = Color(0xFF141218)
    private val onBackgroundDarkMediumContrast = Color(0xFFE6E0E9)
    private val surfaceDarkMediumContrast = Color(0xFF141218)
    private val onSurfaceDarkMediumContrast = Color(0xFFFFF9FF)
    private val surfaceVariantDarkMediumContrast = Color(0xFF49454E)
    private val onSurfaceVariantDarkMediumContrast = Color(0xFFCEC8D4)
    private val outlineDarkMediumContrast = Color(0xFFA6A1AB)
    private val outlineVariantDarkMediumContrast = Color(0xFF86818B)
    private val scrimDarkMediumContrast = Color(0xFF000000)
    private val inverseSurfaceDarkMediumContrast = Color(0xFFE6E0E9)
    private val inverseOnSurfaceDarkMediumContrast = Color(0xFF2B292F)
    private val inversePrimaryDarkMediumContrast = Color(0xFF4E3F77)
    private val surfaceDimDarkMediumContrast = Color(0xFF141218)
    private val surfaceBrightDarkMediumContrast = Color(0xFF3B383E)
    private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0F0D13)
    private val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1B20)
    private val surfaceContainerDarkMediumContrast = Color(0xFF211F24)
    private val surfaceContainerHighDarkMediumContrast = Color(0xFF2B292F)
    private val surfaceContainerHighestDarkMediumContrast = Color(0xFF36343A)

    private val primaryDarkHighContrast = Color(0xFFFFF9FF)
    private val onPrimaryDarkHighContrast = Color(0xFF000000)
    private val primaryContainerDarkHighContrast = Color(0xFFD3C1FF)
    private val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
    private val secondaryDarkHighContrast = Color(0xFFFFF9FF)
    private val onSecondaryDarkHighContrast = Color(0xFF000000)
    private val secondaryContainerDarkHighContrast = Color(0xFFD3C1FF)
    private val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
    private val tertiaryDarkHighContrast = Color(0xFFFFF9F9)
    private val onTertiaryDarkHighContrast = Color(0xFF000000)
    private val tertiaryContainerDarkHighContrast = Color(0xFFFFB7CD)
    private val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
    private val errorDarkHighContrast = Color(0xFFFFF9F9)
    private val onErrorDarkHighContrast = Color(0xFF000000)
    private val errorContainerDarkHighContrast = Color(0xFFFFB9B3)
    private val onErrorContainerDarkHighContrast = Color(0xFF000000)
    private val backgroundDarkHighContrast = Color(0xFF141218)
    private val onBackgroundDarkHighContrast = Color(0xFFE6E0E9)
    private val surfaceDarkHighContrast = Color(0xFF141218)
    private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    private val surfaceVariantDarkHighContrast = Color(0xFF49454E)
    private val onSurfaceVariantDarkHighContrast = Color(0xFFFFF9FF)
    private val outlineDarkHighContrast = Color(0xFFCEC8D4)
    private val outlineVariantDarkHighContrast = Color(0xFFCEC8D4)
    private val scrimDarkHighContrast = Color(0xFF000000)
    private val inverseSurfaceDarkHighContrast = Color(0xFFE6E0E9)
    private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    private val inversePrimaryDarkHighContrast = Color(0xFF2F2056)
    private val surfaceDimDarkHighContrast = Color(0xFF141218)
    private val surfaceBrightDarkHighContrast = Color(0xFF3B383E)
    private val surfaceContainerLowestDarkHighContrast = Color(0xFF0F0D13)
    private val surfaceContainerLowDarkHighContrast = Color(0xFF1D1B20)
    private val surfaceContainerDarkHighContrast = Color(0xFF211F24)
    private val surfaceContainerHighDarkHighContrast = Color(0xFF2B292F)
    private val surfaceContainerHighestDarkHighContrast = Color(0xFF36343A)

    val lightScheme =
        lightColorScheme(
            primary = primaryLight,
            onPrimary = onPrimaryLight,
            primaryContainer = primaryContainerLight,
            onPrimaryContainer = onPrimaryContainerLight,
            secondary = secondaryLight,
            onSecondary = onSecondaryLight,
            secondaryContainer = secondaryContainerLight,
            onSecondaryContainer = onSecondaryContainerLight,
            tertiary = tertiaryLight,
            onTertiary = onTertiaryLight,
            tertiaryContainer = tertiaryContainerLight,
            onTertiaryContainer = onTertiaryContainerLight,
            error = errorLight,
            onError = onErrorLight,
            errorContainer = errorContainerLight,
            onErrorContainer = onErrorContainerLight,
            background = backgroundLight,
            onBackground = onBackgroundLight,
            surface = surfaceLight,
            onSurface = onSurfaceLight,
            surfaceVariant = surfaceVariantLight,
            onSurfaceVariant = onSurfaceVariantLight,
            outline = outlineLight,
            outlineVariant = outlineVariantLight,
            scrim = scrimLight,
            inverseSurface = inverseSurfaceLight,
            inverseOnSurface = inverseOnSurfaceLight,
            inversePrimary = inversePrimaryLight,
            surfaceDim = surfaceDimLight,
            surfaceBright = surfaceBrightLight,
            surfaceContainerLowest = surfaceContainerLowestLight,
            surfaceContainerLow = surfaceContainerLowLight,
            surfaceContainer = surfaceContainerLight,
            surfaceContainerHigh = surfaceContainerHighLight,
            surfaceContainerHighest = surfaceContainerHighestLight,
        )

    val darkScheme =
        darkColorScheme(
            primary = primaryDark,
            onPrimary = onPrimaryDark,
            primaryContainer = primaryContainerDark,
            onPrimaryContainer = onPrimaryContainerDark,
            secondary = secondaryDark,
            onSecondary = onSecondaryDark,
            secondaryContainer = secondaryContainerDark,
            onSecondaryContainer = onSecondaryContainerDark,
            tertiary = tertiaryDark,
            onTertiary = onTertiaryDark,
            tertiaryContainer = tertiaryContainerDark,
            onTertiaryContainer = onTertiaryContainerDark,
            error = errorDark,
            onError = onErrorDark,
            errorContainer = errorContainerDark,
            onErrorContainer = onErrorContainerDark,
            background = backgroundDark,
            onBackground = onBackgroundDark,
            surface = surfaceDark,
            onSurface = onSurfaceDark,
            surfaceVariant = surfaceVariantDark,
            onSurfaceVariant = onSurfaceVariantDark,
            outline = outlineDark,
            outlineVariant = outlineVariantDark,
            scrim = scrimDark,
            inverseSurface = inverseSurfaceDark,
            inverseOnSurface = inverseOnSurfaceDark,
            inversePrimary = inversePrimaryDark,
            surfaceDim = surfaceDimDark,
            surfaceBright = surfaceBrightDark,
            surfaceContainerLowest = surfaceContainerLowestDark,
            surfaceContainerLow = surfaceContainerLowDark,
            surfaceContainer = surfaceContainerDark,
            surfaceContainerHigh = surfaceContainerHighDark,
            surfaceContainerHighest = surfaceContainerHighestDark,
        )

    private val mediumContrastLightColorScheme =
        lightColorScheme(
            primary = primaryLightMediumContrast,
            onPrimary = onPrimaryLightMediumContrast,
            primaryContainer = primaryContainerLightMediumContrast,
            onPrimaryContainer = onPrimaryContainerLightMediumContrast,
            secondary = secondaryLightMediumContrast,
            onSecondary = onSecondaryLightMediumContrast,
            secondaryContainer = secondaryContainerLightMediumContrast,
            onSecondaryContainer = onSecondaryContainerLightMediumContrast,
            tertiary = tertiaryLightMediumContrast,
            onTertiary = onTertiaryLightMediumContrast,
            tertiaryContainer = tertiaryContainerLightMediumContrast,
            onTertiaryContainer = onTertiaryContainerLightMediumContrast,
            error = errorLightMediumContrast,
            onError = onErrorLightMediumContrast,
            errorContainer = errorContainerLightMediumContrast,
            onErrorContainer = onErrorContainerLightMediumContrast,
            background = backgroundLightMediumContrast,
            onBackground = onBackgroundLightMediumContrast,
            surface = surfaceLightMediumContrast,
            onSurface = onSurfaceLightMediumContrast,
            surfaceVariant = surfaceVariantLightMediumContrast,
            onSurfaceVariant = onSurfaceVariantLightMediumContrast,
            outline = outlineLightMediumContrast,
            outlineVariant = outlineVariantLightMediumContrast,
            scrim = scrimLightMediumContrast,
            inverseSurface = inverseSurfaceLightMediumContrast,
            inverseOnSurface = inverseOnSurfaceLightMediumContrast,
            inversePrimary = inversePrimaryLightMediumContrast,
            surfaceDim = surfaceDimLightMediumContrast,
            surfaceBright = surfaceBrightLightMediumContrast,
            surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
            surfaceContainerLow = surfaceContainerLowLightMediumContrast,
            surfaceContainer = surfaceContainerLightMediumContrast,
            surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
            surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
        )

    private val highContrastLightColorScheme =
        lightColorScheme(
            primary = primaryLightHighContrast,
            onPrimary = onPrimaryLightHighContrast,
            primaryContainer = primaryContainerLightHighContrast,
            onPrimaryContainer = onPrimaryContainerLightHighContrast,
            secondary = secondaryLightHighContrast,
            onSecondary = onSecondaryLightHighContrast,
            secondaryContainer = secondaryContainerLightHighContrast,
            onSecondaryContainer = onSecondaryContainerLightHighContrast,
            tertiary = tertiaryLightHighContrast,
            onTertiary = onTertiaryLightHighContrast,
            tertiaryContainer = tertiaryContainerLightHighContrast,
            onTertiaryContainer = onTertiaryContainerLightHighContrast,
            error = errorLightHighContrast,
            onError = onErrorLightHighContrast,
            errorContainer = errorContainerLightHighContrast,
            onErrorContainer = onErrorContainerLightHighContrast,
            background = backgroundLightHighContrast,
            onBackground = onBackgroundLightHighContrast,
            surface = surfaceLightHighContrast,
            onSurface = onSurfaceLightHighContrast,
            surfaceVariant = surfaceVariantLightHighContrast,
            onSurfaceVariant = onSurfaceVariantLightHighContrast,
            outline = outlineLightHighContrast,
            outlineVariant = outlineVariantLightHighContrast,
            scrim = scrimLightHighContrast,
            inverseSurface = inverseSurfaceLightHighContrast,
            inverseOnSurface = inverseOnSurfaceLightHighContrast,
            inversePrimary = inversePrimaryLightHighContrast,
            surfaceDim = surfaceDimLightHighContrast,
            surfaceBright = surfaceBrightLightHighContrast,
            surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
            surfaceContainerLow = surfaceContainerLowLightHighContrast,
            surfaceContainer = surfaceContainerLightHighContrast,
            surfaceContainerHigh = surfaceContainerHighLightHighContrast,
            surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
        )

    private val mediumContrastDarkColorScheme =
        darkColorScheme(
            primary = primaryDarkMediumContrast,
            onPrimary = onPrimaryDarkMediumContrast,
            primaryContainer = primaryContainerDarkMediumContrast,
            onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
            secondary = secondaryDarkMediumContrast,
            onSecondary = onSecondaryDarkMediumContrast,
            secondaryContainer = secondaryContainerDarkMediumContrast,
            onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
            tertiary = tertiaryDarkMediumContrast,
            onTertiary = onTertiaryDarkMediumContrast,
            tertiaryContainer = tertiaryContainerDarkMediumContrast,
            onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
            error = errorDarkMediumContrast,
            onError = onErrorDarkMediumContrast,
            errorContainer = errorContainerDarkMediumContrast,
            onErrorContainer = onErrorContainerDarkMediumContrast,
            background = backgroundDarkMediumContrast,
            onBackground = onBackgroundDarkMediumContrast,
            surface = surfaceDarkMediumContrast,
            onSurface = onSurfaceDarkMediumContrast,
            surfaceVariant = surfaceVariantDarkMediumContrast,
            onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
            outline = outlineDarkMediumContrast,
            outlineVariant = outlineVariantDarkMediumContrast,
            scrim = scrimDarkMediumContrast,
            inverseSurface = inverseSurfaceDarkMediumContrast,
            inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
            inversePrimary = inversePrimaryDarkMediumContrast,
            surfaceDim = surfaceDimDarkMediumContrast,
            surfaceBright = surfaceBrightDarkMediumContrast,
            surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
            surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
            surfaceContainer = surfaceContainerDarkMediumContrast,
            surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
            surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
        )

    private val highContrastDarkColorScheme =
        darkColorScheme(
            primary = primaryDarkHighContrast,
            onPrimary = onPrimaryDarkHighContrast,
            primaryContainer = primaryContainerDarkHighContrast,
            onPrimaryContainer = onPrimaryContainerDarkHighContrast,
            secondary = secondaryDarkHighContrast,
            onSecondary = onSecondaryDarkHighContrast,
            secondaryContainer = secondaryContainerDarkHighContrast,
            onSecondaryContainer = onSecondaryContainerDarkHighContrast,
            tertiary = tertiaryDarkHighContrast,
            onTertiary = onTertiaryDarkHighContrast,
            tertiaryContainer = tertiaryContainerDarkHighContrast,
            onTertiaryContainer = onTertiaryContainerDarkHighContrast,
            error = errorDarkHighContrast,
            onError = onErrorDarkHighContrast,
            errorContainer = errorContainerDarkHighContrast,
            onErrorContainer = onErrorContainerDarkHighContrast,
            background = backgroundDarkHighContrast,
            onBackground = onBackgroundDarkHighContrast,
            surface = surfaceDarkHighContrast,
            onSurface = onSurfaceDarkHighContrast,
            surfaceVariant = surfaceVariantDarkHighContrast,
            onSurfaceVariant = onSurfaceVariantDarkHighContrast,
            outline = outlineDarkHighContrast,
            outlineVariant = outlineVariantDarkHighContrast,
            scrim = scrimDarkHighContrast,
            inverseSurface = inverseSurfaceDarkHighContrast,
            inverseOnSurface = inverseOnSurfaceDarkHighContrast,
            inversePrimary = inversePrimaryDarkHighContrast,
            surfaceDim = surfaceDimDarkHighContrast,
            surfaceBright = surfaceBrightDarkHighContrast,
            surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
            surfaceContainerLow = surfaceContainerLowDarkHighContrast,
            surfaceContainer = surfaceContainerDarkHighContrast,
            surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
            surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
        )
}
